server {
  listen 80;
  server_name localhost; 

  root /usr/share/nginx/html;
  index index.html index.htm;

  location / {
    # kluczowa linijka do React Router
    try_files $uri /index.html;
  }

  #ewentualnie jeśli chcesz proxy do backendu np. /api -> backend:5000
  location /api/ {
    proxy_pass http://app-backend:5000/api/;
  }
}
